README.md
src/Blocks/Block.php
src/Blocks/BlockFactory.php
src/Blocks/Breadcrumb.php
tests/Unit/Blocks/BreadcrumbTest.php

Breadcrumb block

---

.github/workflows/tests.yml

Fix Psalm typo

---

.gitattributes
.github/workflows/ci.yml
.gitignore
composer.lock

Run tests with locked dependencies

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
composer.lock
src/Client.php
src/Databases/Client.php
src/Pages/Client.php
src/Users/Bot.php
src/Users/Client.php
src/Users/User.php

Use PSR interfaces

---

phpunit.xml

Convert PHP deprecations to exceptions

---

.github/workflows/ci.yml
composer.json
composer.lock
phpcs.xml
src/Blocks/Block.php
src/Blocks/BlockFactory.php
src/Blocks/Bookmark.php
src/Blocks/Breadcrumb.php
src/Blocks/ChildDatabase.php
src/Blocks/ChildPage.php
src/Blocks/Code.php
src/Blocks/Divider.php
src/Blocks/Embed.php
src/Blocks/EquationBlock.php
src/Blocks/FileBlock.php
src/Blocks/Heading1.php
src/Blocks/Heading2.php
src/Blocks/Heading3.php
src/Blocks/Image.php
src/Blocks/Pdf.php
src/Blocks/TableOfContents.php
src/Blocks/Video.php
src/Databases/Database.php
src/Databases/Properties/Factory.php
src/NotionException.php
src/Pages/Properties/Factory.php

Check code style

---

src/Blocks/Block.php
src/Blocks/Code.php
src/Common/Mention.php
src/Databases/Properties/Factory.php
src/Databases/Properties/Files.php
src/Databases/Properties/Property.php
src/Pages/Properties/Factory.php
src/Pages/Properties/Property.php
src/Users/User.php
tests/Unit/Common/MentionTest.php
tests/Unit/Users/UserTest.php

Use consts on Psalm Json types

---

CHANGELOG.md
src/Blocks/Block.php
src/Blocks/BlockFactory.php
src/Blocks/LinkPreview.php
tests/Unit/Blocks/LinkPreviewTest.php

Add link preview block

---

src/Blocks/Client.php
tests/Integration/BlocksTest.php

Add find block

---

src/Blocks/Client.php
tests/Integration/BlocksTest.php

Add append blocks

---

README.md
src/Notion.php

Upgrade notion version

---

docs/how-to/add-row-to-database.md
docs/how-to/update-a-page.md

Document how to add and update page properties

---

src/Pages/Properties/Factory.php
src/Pages/Properties/Files.php
src/Pages/Properties/Property.php
tests/Unit/Pages/Properties/FilesTest.php

Add missing File page property

---

docs/how-to/find-a-page.md

Document how to get page content

---

.gitignore

Add Intellij Idea default directory .idea to .gitignore so maintainers using Intellij Idea or PHPStorm don't commit those files accidentially

Add Intellij Idea default directory .idea to .gitignore

---

.github/workflows/tests.yml
CHANGELOG.md
src/Databases/Properties/SelectOption.php
src/Pages/Properties/Date.php
src/Pages/Properties/Email.php
src/Pages/Properties/Number.php
src/Pages/Properties/PhoneNumber.php
src/Pages/Properties/Select.php
src/Pages/Properties/Url.php
tests/Integration/DatabasesTest.php
tests/Unit/Pages/Properties/DateTest.php
tests/Unit/Pages/Properties/EmailTest.php
tests/Unit/Pages/Properties/NumberTest.php
tests/Unit/Pages/Properties/PhoneNumberTest.php
tests/Unit/Pages/Properties/SelectTest.php
tests/Unit/Pages/Properties/UrlTest.php

Add support to nullable page properties

---

docs/blocks/Bookmark.md
docs/blocks/BulletedListItem.md
docs/blocks/Callout.md
docs/blocks/Code.md
docs/blocks/Heading.md
docs/blocks/Paragraph.md
docs/getting-started.md
docs/how-to/add-row-to-database.md
docs/how-to/create-a-page.md
docs/how-to/delete-a-page.md
docs/how-to/find-a-page.md
docs/how-to/query-database.md
docs/how-to/update-a-page.md

Reflect breaking changes on documentation

---

.github/workflows/tests.yml
CHANGELOG.md
docs/.vitepress/config.ts
docs/advanced/configuration.md
docs/package.json
src/Blocks/Client.php
src/Configuration.php
src/Databases/Client.php
src/Exceptions/ApiException.php
src/Exceptions/ConflictException.php
src/Infrastructure/Http.php
src/Notion.php
src/Pages/Client.php
src/Users/Client.php
tests/Unit/ConfigurationTest.php
tests/Unit/Exceptions/ApiExceptionTest.php
tests/Unit/Infrastructure/HttpTest.php

Retry when Notion API responds with conflict error

---

CHANGELOG.md
docs/.vitepress/config.ts
docs/page-properties/People.md
docs/page-properties/index.md

Document People page property

---

CHANGELOG.md
phpunit.xml
src/Configuration.php
src/Databases/Database.php
src/Databases/Properties/PropertyCollection.php
src/Pages/Page.php
src/Pages/Properties/PropertyCollection.php
src/Pages/Properties/Title.php
tests/Unit/ConfigurationTest.php
tests/Unit/Databases/DatabaseTest.php
tests/Unit/Databases/Properties/PropertyCollectionTest.php
tests/Unit/Pages/Properties/PropertyCollectionTest.php
tests/Unit/Pages/Properties/TitleTest.php

Property collections

---

CHANGELOG.md
src/Databases/Query/DateFilter.php
src/Databases/Query/Operator.php
tests/Unit/Databases/Query/DateFilterTest.php

feat(database): this week filter

---

src/Common/File.php
src/Pages/Properties/Files.php

fix(common): only send to API file name when set

---

src/Pages/Client.php

add CreatedBy to not updatable props (#249)

fix(Page): add CreatedBy to not updatable props (#249)

---

src/Databases/Properties/PropertyCollection.php
src/Databases/Properties/PropertyFactory.php
src/Databases/Properties/PropertyType.php
src/Databases/Properties/UniqueId.php
src/Pages/Properties/PropertyCollection.php
src/Pages/Properties/PropertyFactory.php
src/Pages/Properties/PropertyType.php
src/Pages/Properties/UniqueId.php
tests/Unit/Databases/Properties/PropertyCollectionTest.php
tests/Unit/Databases/Properties/UniqueIdTest.php
tests/Unit/Pages/Properties/PropertyCollectionTest.php
tests/Unit/Pages/Properties/UniqueIdTest.php

feat: add UniqueId page and database property

---

src/Pages/Client.php

fix(page): do not update Unique ID property

---

src/Pages/Client.php

fix(page): do not update Rollup properties

---

CHANGELOG.md
src/Exceptions/ApiException.php

fix: error when Notion sends an empty response

---

README.md

doc: recommend static analysers

---

src/Databases/Properties/PropertyCollection.php
src/Pages/Properties/PropertyCollection.php

Includes the property name in the exception message when a property is not found.

Improve missing property exception message

---

src/Pages/Client.php

This PR intends to fix [#308](https://github.com/mariosimao/notion-sdk-php/issues/308) by adding Formula property to pages` notUpdatableProps

Fixes #308: Adds formula to pages notUpdatableProps

---

src/Users/User.php

Fix #323  by introducing null fallback for missing optional properties in User::fromArray.

Fixes #323: Use null fallback for missing array keys for optional properties in User::fromArray

---

src/Databases/Database.php
tests/Integration/DatabasesTest.php
tests/Unit/Databases/DatabaseTest.php

**Reference:** https://github.com/mariosimao/notion-sdk-php/issues/119
**Add the possibility to inline a database.**
I updated the unit and integration tests, and they both ran successfully in my environment.
LMK if you want me to change or add anything!

feat: Inline Database
